# -*- coding: utf-8 -*-
"""Clases y Objetos.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fDsup7L4HCDFu4TkgBQQj4DPFQ-kbQ2Y
"""

# Identificacion de Clases y Objetos dados en la secuencia de python
# Programacio Orientada a objetos
# Codigo Modular y reutiliizable
#Objetc oriendet Programing

#Una clase es una plantilla de objetos o intacias segun metodos que eliges

# Ejemplo de una clase

class Persona:
  #Definicion del metodo contructor en la siguiente instancia
  # Es un metodo de la propia clase
  def __init__(self, nombre, edad):
    self.nombre = nombre
    self.edad = edad

  def saludo(self):
    return (f"Hola soy {self.nombre} y tengo {self.edad} años")

  def Verificacion_Mayor_Edad(self):
    if self.edad >= 18:
      return f"yo {self.nombre} Soy Mayor de edad"
    else:
      return f"yo {self.nombre} Soy Menor de edad"


# Creacion de los objetos con sus atributos de inicializacion

Persona1 = Persona("Marcelo", 28)
Persona2 = Persona("Javier", 15)

# Impresion y salida del metodo saludo

print(Persona1.saludo())
print(Persona2.saludo())

# Impresion y salida del metodo mayor de edad

print(Persona1.Verificacion_Mayor_Edad())
print(Persona2.Verificacion_Mayor_Edad())

class Animal:
  def __init__(self, nombre, especie, edad):
    self.nombre = nombre
    self.especie = especie
    self.edad = edad

  def descripcion(self):
    print(f"{self.nombre} es un {self.especie} y tiene {self.edad} años")

# Declaracion de los objetos

Animal1 = Animal("Tijuana","Gato", 18)
Animal2 = Animal("Geronimo", "Perro", 3)

# Impresion
Animal1.descripcion()
Animal2.descripcion()

class CuentaBancaria:
  def __init__(self, titular, numero_cuenta, saldo=0): # En esta instancia se pueden definir los valores por defecto que pueden tener los objetos cuando no se pongan los valores registrados

    self.titular = titular
    self.numero_cuenta = numero_cuenta
    self.saldo = saldo

  def depositar_dinero(self, monto):
    self.saldo += monto
    print(f"Se ha depositado {monto} en la cuenta de {self.titular}, el saldo actual es de {self.saldo}")


CuentaBancaria1 = CuentaBancaria("Marcelo","91222526791",2000)
CuentaBancaria2 = CuentaBancaria("Raul", "91225263021", 3000)

CuentaBancaria1.depositar_dinero(1000)
CuentaBancaria2.depositar_dinero(2000)